### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Scribe/Scribe-i18n](https://hosted.weblate.org/projects/scribe/scribe-i18n/).

Current translation status:

<a href="https://hosted.weblate.org/engage/scribe/">
Translation status
</a>

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for the translations so far, @henrikth93! @Jag-Marcel, do you think you'll be able to get to German over say the coming week? :)

**Comment by Jag-Marcel** [comment]
@andrewtavis I'll try to get them in today

**Comment by andrewtavis** [comment]
Nice, thanks @Jag-Marcel! :)

**Comment by andrewtavis** [comment]
Thanks, @Jag-Marcel! @henrikth93, would you be able to get to the rest of the Swedish soon? :)

**Comment by henrikth93** [comment]
> Thanks, @Jag-Marcel! @henrikth93, would you be able to get to the rest of the Swedish soon? :)

Will sit with them today

**Comment by andrewtavis** [comment]
Awesome! Looking forward 😊

**Comment by andrewtavis** [comment]
Looks like Swedish is now at 100%, actually :) Was that you, @henrikth93? Should I bring them in to this PR and we can merge?

**Comment by henrikth93** [comment]
> Looks like Swedish is now at 100%, actually :) Was that you, @henrikth93? Should I bring them in to this PR and we can merge?

I am pretty sure it was me! Go ahead! :D

**Review by andrewtavis — APPROVED** [review]
Amazing 🤩 Thank you both so much! I'll move these over into the repos now 😊

**Pull request merged**
