### PR TITLE
fix:Added escape character for \n

### PR DESCRIPTION
**Pull request by angrezichatterbox**
The pull request implements escape characters for \n so that the string.xml would have a \n instead of a new line coming up.

#27

### CODE REVIEW

**Comment by andrewtavis** [comment]
Just checking here, @angrezichatterbox, with this we do not need to change anything for the strings in Scribe-Android and they'll just be good to go?

**Comment by angrezichatterbox** [comment]
> Just checking here, @angrezichatterbox, with this we do not need to change anything for the strings in Scribe-Android and they'll just be good to go?

I have cross-checked the strings. I assume there aren't any more escape characters to add to the current set of strings. I have taken in most of the cases possible.

**Comment by andrewtavis** [comment]
Ok, nice :) I'll merge this soon and then move it over to the Android PR :)

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @angrezichatterbox! Really appreciate you coming in with such a quick fix 🙏

**Pull request merged**
