### PR TITLE
Create hi.json

### PR DESCRIPTION
**Pull request by KesharwaniArpita**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have searched [open localization issues](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [x] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

---

### Description

This PR add in an `hi.json` file to the [Scribe-i18n/jsons](https://github.com/scribe-org/Scribe-i18n/tree/main/Scribe-i18n/jsons) directory with a localizations based on [Scribe-i18n/jsons/en-US.json](https://github.com/scribe-org/Scribe-i18n/blob/main/Scribe-i18n/jsons/en-US.json). This would thus start the i18n process for this language, with it also being added on to Scribe's [Weblate project](https://hosted.weblate.org/projects/scribe/scribe-i18n/) for further work.

1. The file is based on `en-US.json`.
2. The translations are done with the help of various internet translation tools available and cross-validated by me.

### Related issue

- #51

### CODE REVIEW

**Comment by andrewtavis** [comment]
Amazing, @KesharwaniArpita 🤩 This is so cool 😊 I'll bring this in later and set it up on Weblate :)

**Comment by KesharwaniArpita** [comment]
Thank you Andrew!!!

**Review by andrewtavis — APPROVED** [review]
Really appreciate the great work here, @KesharwaniArpita! Growing Scribe within the South Asian language community is such a great step, as until now it's just been European languages. Thanks so much for helping us take this step!

**Comment by KesharwaniArpita** [comment]
I am really glad to contribute!!

**Pull request merged**
