### PR TITLE
Fixing a typo in readme.md

### PR DESCRIPTION
**Pull request by OmarAI2003**
This PR fixes a minor typo in the README.md file. I changed "an tools" to "tools".

### CODE REVIEW

**Comment by OmarAI2003** [comment]
.

**Comment by OmarAI2003** [comment]
I’m closing this PR because it unintentionally includes commits from another branch . I created a new branch directly from `main` for the typo fix and will open a new PR for it. Sorry for the confusion!

**Comment by andrewtavis** [comment]
I thought this had been merged, or was that in a downstream project, @OmarAI2003?

**Comment by andrewtavis** [comment]
We should do something with this here?

**Comment by OmarAI2003** [comment]
No It was in another repo the Data repo

**Comment by andrewtavis** [comment]
Just saw the comment above. All good!

**Comment by andrewtavis** [comment]
Thanks for the explanation!

**Pull request closed without merging**
