### PR TITLE
Conversion from JSON to XML

### PR DESCRIPTION
**Pull request by angrezichatterbox**
The pull request adds conversion from JSON to XML and XML to JSON. The new scripts are present in the Scripts Folder. The XML files would be generated in a values folder with each XML strings file under its own language folder. 

- #27

### CODE REVIEW

**Comment by andrewtavis** [comment]
Generally looking really good, @angrezichatterbox! Can I just check that the `values` directory is something that's standard in other Android projects. To me it seems like a more descriptive name would be better, but happy to keep it as is if this is what you've seen in other projects!

Sending a commit with some minor changes and the included files shortly 😊

**Comment by angrezichatterbox** [comment]
In some Android projects I've worked on previously, I've seen values organized in the res folder with multiple languages within each values folder. Should I consider changing the format to this approach?

**Comment by andrewtavis** [comment]
No I guess this is fine, @angrezichatterbox :) Just checking to see if `values` should be `localization` or something like that. We can also change it later 😊

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @angrezichatterbox! We'll bring in these to the Android project later on today 🌐🤖

**Pull request merged**
